drop table truckGoodsReport
  GO
  CREATE TABLE truckGoodsReport(
	id int IDENTITY(1,1) NOT NULL,
	truckNumber varchar(99) NULL,
	reportNumber varchar(100) NULL,
	reportId int NULL,
	beginDate varchar(16) NULL,
	expectedDate varchar(16) NULL,
	endDate varchar(16) NULL,
	driver int NULL,
	client int NULL,
	goodsType varchar(100) NULL,
	packageFlg int NULL,
	packagePrice decimal(10, 4) NULL,
	truckPart int NULL,
	partner varchar(100) NULL,
	partnerPrice varchar(100) NULL,
	partnerCarry varchar(100) NULL,
	reportStatus int NULL,
	isLater int NULL,
	laterReason varchar(900) NULL,
	expensens decimal(15, 4) NULL,
	profit decimal(10, 4) NULL,
	cost decimal(10, 4) NULL,
	payAccessory varchar(99) NULL,
	signAccessory varchar(99) NULL,
	checkOutAccessory varchar(99) NULL,
	workPlace varchar(99) NULL,
	remark varchar(1000) NULL,
	carryNumber varchar(100) NULL,
	customerOrder varchar(100) NULL,
	prepaidFlg int NULL,
	prepaidExpress decimal(10, 4) NULL,
	prepaidDesc varchar(200) NULL,
	processingFee decimal(10, 4) NULL,
	loadIsSettle int NULL,
	deleteFlg int NOT NULL,
	lifitingCost decimal(10, 4) NULL,
	oilFee decimal(10, 4) NULL,
	tollFee decimal(10, 4) NULL,
	repairFee decimal(10, 4) NULL,
	tyreFee decimal(10, 4) NULL,
	guideWayFee decimal(10, 4) NULL,
	otherFee decimal(10, 4) NULL,
	allowance decimal(10, 4) NULL,
	forfeit decimal(10, 4) NULL,
	parts decimal(10, 4) NULL,
	breakRulesFee decimal(10, 4) NULL,
	createDate varchar(10) NULL,
	createTime varchar(5) NULL,
	editDate varchar(50) NULL,
	editTime varchar(5) NULL
) 